export const Images = {
    LOGO: require('../assets/images/icon.png'),
    LOGO_ROUND: require('../assets/images/androidIcon.png'),
    ANT_B: require('../assets/images/antb.jpeg'),
    MCDEEZ: require('../assets/mcdonalds/mcd_logo.png'),
    MARKER: require('../assets/icons/marker.png'),
    LOCATION: require('../assets/parralax/mcds.jpeg'),
    OPEN_SIGN: require('../assets/icons/open.png'),
    BEER: require('../assets/icons/beer.png'),
    RESTAURANT: require('../assets/icons/restaurant.png'),
    MARKET: require('../assets/icons/market.png'),
    HEART: require('../assets/icons/heart.png'),
    BEER_NOT: require('../assets/icons/beer-not.png'),
    RESTAURANT_NOT: require('../assets/icons/restaurant-not.png'),
    MARKET_NOT: require('../assets/icons/market-not.png'),
    HEART_NOT: require('../assets/icons/heart-not.png'),
    TABLE: require('../assets/icons/table.png'),

    HAMBURGER: require('../assets/icons/hamburger.png'),
    CHICKEN: require('../assets/icons/fried-chicken.png'),
    FRIES: require('../assets/icons/french-fries.png'),
    COFFEE: require('../assets/icons/coffee-cup.png'),
};
